linters:
  flake8:
  eslint:
    config: './eslint.config'
  csslint:
    ignore: 'order-alphabetical,box-model'
  stylelint:
files:
  ignore:
    - 'old_school/dist/main.js'
    - 'webpack-demo/dist/main.js'
